name: Create pull request from c7n vendor to our branch
on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: cloud-custodian/cloud-custodian
        source_branch: master
        destination_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: master
        destination_branch: stax-provided-patches
        github_token: ${{ secrets.GITHUB_TOKEN }}