name: Create pull request from c7n vendor to our branch
on:
  workflow_dispatch:
    inputs:
      placeholder:
        description: 'Placeholder Value'
        required: false
        default: 'Just holding the place'
  schedule:
  - cron: "*/15 * * * *"

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: cloud-custodian/cloud-custodian
        source_branch: master
        destination_branch: master
        github_token: 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
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: master
        destination_branch: stax-vendored-patches
        github_token: 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
        pr_title: "Update C7N to Master"
        pr_body: ":crown: :cloud: Magic!"